name: check_syntax

on:
  push:
    branches:
      - check_syntax
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ("3.9","3.10","3.11") 
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Update Pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Install flake8
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 --count --statistics --show-source
      
      
