name: check_syntax

on:
  push:
    branches:
      - check_syntax
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      
