name: main

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: windows-latest
            python-version: ("3.9","3.11")
          - operation-system: ubuntu-latest
            python-version: ("3.10")
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Update Pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Install flake8
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 --count --statistics --show-source
      - name: Unittest
        run: |
          pip install versioneer[toml]==0.29
          pip install . --no-deps --no-build-isolation
          python -m unittest discover tests
      
        
