name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - python-version: "3.10"
            os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install flake8
          python -m pip install unittest

      - name: Display Python version
        run: python --version

      - name: Check code style with flake8
        run: flake8

      - name: Run unit tests
        run: python -m unittest
